@api_url = http://localhost:3001/store
@exec_url = http://localhost:3001/execution

### LIST

GET {{api_url}}/boxId/ HTTP/1.1

### CREATE FOO

# @name createElem
POST {{api_url}}/boxId/ HTTP/1.1
content-type: application/json

{
    "name": "foo"
}

### CREATE BAR

POST {{api_url}}/boxId/ HTTP/1.1
content-type: application/json

{
    "name": "bar"
}

### LIST with limit, skip and sort

GET {{api_url}}/boxId/?limit=2&sort=-name&skip=1&fields=name,_id HTTP/1.1

### GET

@elemId = {{createElem.response.body.$._id}}

GET {{api_url}}/boxId/{{elemId}} HTTP/1.1

### UPDATE

@elemId = {{createElem.response.body.$._id}}

PUT {{api_url}}/boxId/{{elemId}} HTTP/1.1
content-type: application/json

{
    "other": "baz"
}

### DELETE

@elemId = {{createElem.response.body.$._id}}

DELETE {{api_url}}/boxId/{{elemId}} HTTP/1.1

# With authentication ########################

### CREATE TIP

# @name createElemKey

POST {{api_url}}/boxId/?key=testkey HTTP/1.1
content-type: application/json

{
    "name": "tip"
}

### UPDATE with good key

@elemIdWithKey = {{createElemKey.response.body.$._id}}

PUT {{api_url}}/boxId/{{elemIdWithKey}}?key=testkey HTTP/1.1
content-type: application/json

{
    "other": "baz"
}


### UPDATE with bad key

@elemIdWithKey = {{createElemKey.response.body.$._id}}

PUT {{api_url}}/boxId/{{elemIdWithKey}}?key=badkey HTTP/1.1
content-type: application/json

{
    "other": "baz"
}

### DELETE with bad key

@elemIdWithKey = {{createElemKey.response.body.$._id}}

DELETE {{api_url}}/boxId/{{elemIdWithKey}}?key=badkey HTTP/1.1

### DELETE with good key

@elemIdWithKey = {{createElemKey.response.body.$._id}}

DELETE {{api_url}}/boxId/{{elemIdWithKey}}?key=testkey HTTP/1.1


# Execution module

### just get test

GET {{exec_url}}/test/?param1=toto HTTP/1.1