version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  lint-and-build:
    executor:
      name: node/default
    environment:
      NETLIFY_SITE_ID: airboardgame.netlify.app
      VITE_SOCKET_URL: https://ricochetjs.herokuapp.com/
      VITE_API_ENDPOINT: /api
      VITE_RICOCHET_SITEID: airboardgame
      VITE_USE_PROXY: 0
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node --version
            - run: npm ci
            - run: npm run lint
            - run: cd backend && npm ci && npm run build
            - run: npm run build
            - run: |
                cat \<<EOF > ./dist/_redirects
                /api/*  https://ricochetjs.herokuapp.com/:splat  200
                /*    /index.html   200
                EOF
            - run:
                name: Netlify Deploy
                command: npx netlify deploy --dir=./dist --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN

  build-deploy:
    executor:
      name: node/default
    environment:
      NETLIFY_SITE_ID: airboardgame.netlify.app
      VITE_SOCKET_URL: https://ricochetjs.herokuapp.com/
      VITE_USE_PROXY: 0
      VITE_API_ENDPOINT: /api
      VITE_RICOCHET_SITEID: airboardgame
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run lint
            - run: cd backend && npm ci && npm run build
            - run: npm run build
            - run: |
                cat \<<EOF > ./dist/_redirects
                /api/*  https://ricochetjs.herokuapp.com/:splat  200
                /*    /index.html   200
                EOF
            - run:
                name: Netlify Deploy
                command: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=dist --prod

workflows:
  build-and-test:
    jobs:
      - lint-and-build:
          filters:
            branches:
              ignore:
                - master
      - build-deploy:
          filters:
            branches:
              only:
                - master
